<?php

/*
 *
 *  ____            _        _   __  __ _                  __  __ ____
 * |  _ \ ___   ___| | _____| |_|  \/  (_)_ __   ___      |  \/  |  _ \
 * | |_) / _ \ / __| |/ / _ \ __| |\/| | | '_ \ / _ \_____| |\/| | |_) |
 * |  __/ (_) | (__|   <  __/ |_| |  | | | | | |  __/_____| |  | |  __/
 * |_|   \___/ \___|_|\_\___|\__|_|  |_|_|_| |_|\___|     |_|  |_|_|
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * @author PocketMine Team
 * @link http://www.pocketmine.net/
 *
 *
 */

declare(strict_types=1);

namespace pocketmine;

/**
 * @internal
 * Constants for all properties available in beeltymine.yml.
 * This is generated by build/generate-pocketmine-yml-property-consts.php.
 * Do not edit this file manually.
 */
final class YmlServerProperties{

	private function __construct(){
		//NOOP
	}

	public const ENTITY_AI = 'entity-ai';
	public const REDSTONE = 'redstone';
	public const REDSTONE_OBSERVER_BLOCK_UPDATE = 'redstone.observer-block-update';
	public const REDSTONE_PISTON_MOVEMENT = 'redstone.piston-movement';
	public const REDSTONE_STATUS = 'redstone.status';
}
